polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

supervisor_menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

trackberry/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Polls app
# urlpatterns += [
#     path('polls/', include('polls.urls')),
# ]

urlpatterns += [
    path('menu/', include('supervisor_menu.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='menu/', permanent=True)),
]

# Use static() to add URL mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

supervisor_menu/models.py
from django.db import models


def add_ten(model):
    largest = model.objects.all().largest


class SupervisorMenuItem(models.Model):

    text = models.CharField(max_length=20, help_text='Menu Item Text')
    url = models.CharField(max_length=40)
    ordering = models.IntegerField(default=1)

    def add_ten(self):
        largest = self.objects.all().largest

    def __str__(self):
        return self.text


class SupervisorSubMenuItem(models.Model):
    text = models.CharField(max_length=20, help_text='Sub menu item text')
    url = models.CharField(max_length=40)
    ordering = models.IntegerField()
    parent = models.ForeignKey('SupervisorMenuItem',
                               blank=True, null=True,
                               related_name='children',
                               on_delete=models.CASCADE)

    def __str__(self):
        return self.text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

supervisor_menu/views.py
from django.shortcuts import render
from .models import SupervisorMenuItem, SupervisorSubMenuItem


def index(request):

    top_items = SupervisorMenuItem.objects.order_by('position').all()
    sub_items = SupervisorSubMenuItem.objects.order_by('position').all()
    menu_list = []
    for item in top_items:
        menu_item = {'text': item.text,
                     'url': item.url,
                     'submenus': []}
        for sub_item in sub_items.filter(parent_id=item.id).order_by('position').all():
            menu_item['submenus'].append({'text': sub_item.text,
                                          'url': sub_item.url})

        menu_list.append(menu_item)

    return render(request, 'index.html', context={'menu_list': menu_list})

polls/templates/polls/detail.html
{% extends "base.html" %}

{% block page_content %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}

{% block page_content %}

      {% if latest_question_list %}
          <ul>
              {% for question in latest_question_list %}
                  <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
              {% endfor %}
          </ul>
      {% else %}
            <p>No polls are available.</p>
      {% endif %}

{% endblock %}

polls/templates/polls/results.html
{% extends "base.html" %}

{% block page_content %}

    <h1>{{ question.question_text }}</h1>

    <ul>{% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}</ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}

supervisor_menu/templates/index.html
{% extends "base.html" %}

{% block page_content %}
{#    <nav class="navbar navbar-expand-lg navbar-light bg-light">#}
{#        <a class="navbar-brand" href="#">Navbar</a>#}
{#        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#            <span class="navbar-toggler-icon"></span>#}
{#        </button>#}
{##}
{#        <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#            <ul class="navbar-nav mr-auto">#}
{#                {% include "menu.html" %}#}
{#            </ul>#}
{#        </div>#}
{#    </nav>#}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

        {% include "menu.html" %}


        {#      <li class="nav-item active">#}
{#        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link" href="#">Link</a>#}
{#      </li>#}
{#      <li class="nav-item dropdown">#}
{#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#          Dropdown#}
{#        </a>#}
{#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#          <a class="dropdown-item" href="#">Action</a>#}
{#          <a class="dropdown-item" href="#">Another action</a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a class="dropdown-item" href="#">Something else here</a>#}
{#        </div>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link disabled" href="#">Disabled</a>#}
{#      </li>#}
    </ul>
  </div>
</nav>
{% endblock %}

supervisor_menu/templates/menu.html
{% for menu in menu_list %}
    {% if menu.submenus|length %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    {% else %}
        <li class="nav-item">
            <a class="nav-item">
    {% endif %}
                {{ menu.text }}
            </a>
    {% if menu.submenus|length %}
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% include "sub_menu.html" with sub_menu_list=menu.submenus %}
        </div>
    {% endif %}
        </li>
{% endfor %}

supervisor_menu/templates/sub_menu.html
{% for item in sub_menu_list %}
    {%  if item.name == "-" %}
        <div class="dropdown-divider"></div>
    {% else %}
        <a class="dropdown-item dropdown" href="{{ item.url }}">{{ item.text }}</a>
    {% endif %}
{% endfor %}

trackberry/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>

{% block page_content %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>